blogicum/apps/blog/urls.py
from django.urls import path

from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts',
    ),
]

blogicum/apps/pages/urls.py
from django.urls import path

from pages import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blogicum/blogicum/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

blogicum/apps/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone

from core.models import (
    DateCreatedModel,
    PublishedModel,
)

User = get_user_model()


class PostQuerySet(models.QuerySet):
    """Custom query set for post model."""

    def get_published_posts(self) -> models.QuerySet:
        """Fetch posts which are published.

        Published posts are not either:
        1. Have is_published flag set to False.
        2. Belong to category with is_published flag set to False.
        3. Have pub_date greater than now.
        """
        return self.filter(
            is_published=True,
            category__is_published=True,
            pub_date__lte=timezone.now(),
        )

    def select_all_related(self) -> models.QuerySet:
        """Select all foreign keys for the posts."""
        return self.select_related('author', 'category', 'location')


class Category(PublishedModel, DateCreatedModel):
    """Category of posts by the same theme."""

    title = models.CharField(
        max_length=256,
        verbose_name='Заголовок',
    )
    slug = models.SlugField(
        verbose_name='Идентификатор',
        unique=True,
        help_text=(
            'Идентификатор страницы для URL; разрешены'
            ' символы латиницы, цифры, дефис и подчёркивание.'
        ),
    )
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.title


class Location(PublishedModel, DateCreatedModel):
    """Some landmark."""

    name = models.CharField(
        max_length=256,
        verbose_name='Название места',
    )

    class Meta:
        verbose_name = 'местоположение'
        verbose_name_plural = 'Местоположения'

    def __str__(self) -> str:
        return self.name


class Post(PublishedModel, DateCreatedModel):
    """A single post."""

    title = models.CharField(
        max_length=256,
        verbose_name='Заголовок',
    )
    text = models.TextField(
        verbose_name='Текст',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата и время публикации',
        help_text=(
            'Если установить дату и время в будущем'
            ' — можно делать отложенные публикации.'
        ),
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор публикации',
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts',
        verbose_name='Местоположение',
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        related_name='posts',
        verbose_name='Категория',
    )

    objects = PostQuerySet.as_manager()

    class Meta:
        verbose_name = 'публикация'
        verbose_name_plural = 'Публикации'
        ordering = ('-pub_date',)

    def __str__(self) -> str:
        return f'{self.pub_date} - {self.title}'

blogicum/apps/core/models.py
from django.db import models


class PublishedModel(models.Model):
    is_published = models.BooleanField(
        default=True, verbose_name='Опубликовано',
        help_text='Снимите галочку, чтобы скрыть публикацию.'
    )

    class Meta:
        abstract = True


class DateCreatedModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name='Добавлено'
    )

    class Meta:
        abstract = True

blogicum/apps/pages/models.py
# Create your models here.

blogicum/apps/blog/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404, render

from blog.models import Category, Post


def index(request: HttpRequest) -> HttpResponse:
    """Show project main page.

    Args:
        request (HttpRequest): Request received from the user.
    """
    template = 'blog/index.html'

    posts = Post.objects.select_all_related().get_published_posts()[:5]
    context = {'post_list': posts}
    return render(request, template, context)


def post_detail(request: HttpRequest, id: int) -> HttpResponse:  # noqa: A002
    """Show post content.

    Args:
        request (HttpRequest): Request received from the user.
        id (int): Post id.
    """
    template = 'blog/detail.html'
    required_post = get_object_or_404(
        Post.objects.select_all_related().get_published_posts(),
        pk=id,
    )

    context = {'post': required_post}
    return render(request, template, context)


def category_posts(request: HttpRequest, category_slug: str) -> HttpResponse:
    """Show list of posts in a category.

    Args:
        request (HttpRequest): Request received from the user.
        category_slug (str): Category identifier.
    """
    template = 'blog/category.html'
    category = get_object_or_404(
        Category.objects.filter(is_published=True),
        slug=category_slug,
    )
    posts = category.posts.select_all_related().get_published_posts()
    context = {'category': category.title, 'post_list': posts}
    return render(request, template, context)

blogicum/apps/pages/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render


def about(request: HttpRequest) -> HttpResponse:
    """Show page with info about the project.

    Args:
        request (HttpRequest): Request received from the user.
    """
    template = 'pages/about.html'
    return render(request, template)


def rules(request: HttpRequest) -> HttpResponse:
    """Show page with rules.

    Args:
        request (HttpRequest): Request received from the user.
    """
    template = 'pages/rules.html'
    return render(request, template)

blogicum/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon"
          sizes="180x180"
          href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon"
          type="image/png"
          sizes="32x32"
          href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon"
          type="image/png"
          sizes="16x16"
          href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>
      {% block title %}{% endblock %}
    </title>
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
        {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}
  </body>
</html>

blogicum/templates/blog/category.html
{% extends "base.html" %}
{% block title %}Публикации в категории {{ category }}{% endblock %}
{% block content %}
  <h1>Публикации в категории «{{ category.title }}»</h1>
  <p class="mb-5">{{ category.description }}</p>
  {% for post in post_list %}
    <article class="mb-5">{% include "includes/post_card.html" %}</article>
  {% endfor %}
{% endblock %}

blogicum/templates/blog/category_posts.html
{% extends "base.html" %}
{% block title %}Публикации в категории {{ category }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Публикации в категории {{ category }}</h1>
  </div>
{% endblock %}

blogicum/templates/blog/detail.html
{% extends "base.html" %}
{% block title %}{{ post.location }}. {{ post.date }}{% endblock %}
{% block content %}
  <article>
    <p>
      {{ post.pub_date|date:"d E Y" }} |
      {% if post.location and post.location.is_published %}
        {{ post.location.name }}
      {% else %}
        Планета Земля
      {% endif %}
      <br>
      <small>От автора @{{ post.author.username }} в категории
        {% include "includes/category_link.html" %}
      </small>
    </p>
    <h3>{{ post.title }}</h3>
    <p>{{ post.text|linebreaksbr }}</p>
  </article>
{% endblock %}

blogicum/templates/blog/index.html
{% extends "base.html" %}
{% block title %}Лента записей{% endblock %}
{% block content %}
  <h1 class="mb-5">Лента записей</h1>
  {% for post in post_list %}
    <article class="mb-5">{% include "includes/post_card.html" %}</article>
  {% endfor %}
{% endblock %}

blogicum/templates/blog/post_detail.html
{% extends "base.html" %}
{% block title %}{{ post.location }}. {{ post.date }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <article>
      <ul>
        <li>Место: {{ post.location }}</li>
        <li>Дата: {{ post.date }}</li>
        <li>
          Категория: <a href="{% url 'blog:category_posts' post.category %}">{{ post.category }}</a>
        </li>
      </ul>
      <p>
        {{ post.text|linebreaksbr }}
      </p>
    </article>
  </div>
{% endblock %}

blogicum/templates/includes/category_link.html
<a class="text-muted" href="{% url 'blog:category_posts' post.category.slug %}">
  «{{ post.category.title }}»
</a>

blogicum/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© Блогикум</p>    
</footer>

blogicum/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light bg-lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index' %}">
        <img src="{% static 'img/logo.png' %}"
             width="30"
             height="30"
             class="d-inline-block align-top"
             alt="Логотип">
        Блогикум
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav  nav-pills">
        {% include "includes/nav-item.html" with nav_url="blog:index" label="Лента записей" %}
        {% include "includes/nav-item.html" with nav_url="pages:about" label="О проекте" %}
        {% include "includes/nav-item.html" with nav_url="pages:rules" label="Наши правила" %}
      </ul>
      {% endwith %}
    </div>
  </nav>
</header>

blogicum/templates/includes/nav-item.html
{% with request.resolver_match.view_name as view_name %}
  <li class="nav-item">
    <a class="nav-link {% if view_name == nav_url %}active{% endif %}"
       href="{% url nav_url %}">{{ label }}</a>
  </li>
{% endwith %}

blogicum/templates/includes/post_card.html
<div class="card post-card">
  <div class="card-body">
    <h5 class="card-title">{{ post.title }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">
      <small>
        {{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
        От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}
      </small>
    </h6>
    <p class="card-text">{{ post.text|truncatewords:10 }}</p>
    <a href="{% url 'blog:post_detail' post.id %}" class="card-link">Читать полный текст</a>
  </div>
</div>

blogicum/templates/pages/about.html
{% extends "base.html" %}
{% block title %}О проекте{% endblock %}
{% block content %}
  <h1>О проекте</h1>
  <p>
    Блогикум — это дом для творческих людей. Это — сообщество людей, для которых
    нет грани между ведением блога и дружбой в социальных сетях.
  </p>
  <p>
    Дружба и рассказы о новых, неизведанных впечатлениях — вот
    что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам.
    Путешествия, политики, развлечения, мода, мода, литература, дизайн и все
    другие сферы человеческой деятельности.
  </p>
  <p>
    Творчество, разнообразие и свобода взглядов и самовыражения —
    основные черты наших пользователей.
  </p>
{% endblock %}

blogicum/templates/pages/rules.html
{% extends "base.html" %}
{% block title %}Наши правила{% endblock %}
{% block content %}
  <h1>Наши правила</h1>
  <p>
    <b>Cамовыражение.</b> У наших пользователей должна
    быть возможность создать что-то своё, выразить себя,
    свои мысли и чувства.
  </p>
  <p>
    <b>Многообразие.</b> Мы уважаем и приветствуем разные
    мнения и культуры. Блогикум — это место, объединяющее
    самых разных людей. Поделитесь своим уникальным взглядом на мир.
  </p>
  <p>
    <b>Творчество.</b> Не важно, в какой области вы творите,
    это может быть литература, дизайн, программирование.
    Наши инструменты помогут вам раскрыть талант максимально
    просто и комфортно.
  </p>
  <p>
    <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне.
    Делитесь своей информацией только с теми, кого выбрали.
    Как и насколько засекречивать вашу личную информацию —
    определяете вы и только вы.
  </p>
{% endblock %}

templates/blog/category.html
{% extends "base.html" %}
{% block title %}
  Публикации в категории «{{ category.title }}»
{% endblock %}
{% block content %}
<h1>Публикации в категории «{{ category.title }}»</h1>
<p class="mb-5">{{ category.description }}</p>
{% for post in post_list %}
  <article class="mb-5">  
    {% include "includes/post_card.html" %}
  </article>   
{% endfor %}

{% endblock %}

templates/blog/detail.html
{% extends "base.html" %}
{% block title %}
{{ post.title }} | {% if post.location and post.location.is_published %}{{ post.location.name }} |{% endif %} {{ post.pub_date|date:"d E Y" }}
{% endblock %}
{% block content %}
  <article>
    <p>{{ post.pub_date|date:"d E Y" }} | {% if post.location and post.location.is_published %}{{ post.location.name }}{% else %}Планета Земля{% endif %}<br>
      <small>От автора @{{ post.author.username }} в категории {% include "includes/category_link.html" %}</small></p>
    <h3>{{ post.title }}</h3>
    <p>{{ post.text|linebreaksbr }}</p>
  </article> 
{% endblock %}

templates/blog/index.html
{% extends "base.html" %}
{% block title %}
  Лента записей
{% endblock %}
{% block content %}
  <h1 class="mb-5">Лента записей</h1>
  {% for post in post_list %}
    <article class="mb-5">  
      {% include "includes/post_card.html" %}
    </article>   
  {% endfor %}
{% endblock %}

templates/pages/about.html
{% extends "base.html" %}
{% block title %}
  О проекте
{% endblock %}
{% block content %}
  <h1>О проекте</h1>
  <p>
    Блогикум — это дом для творческих людей. Это — сообщество людей, для которых 
    нет грани между ведением блога и дружбой в социальных сетях. 
  </p>
  <p>
    Дружба и рассказы о новых, неизведанных впечатлениях — вот 
    что вы найдете на нашем ресурсе.  Миллионы блогов по различным темам. 
    Путешествия, политики, развлечения, мода, мода, литература, дизайн и все 
    другие сферы человеческой деятельности. 
  </p>
  <p>
    Творчество, разнообразие и свобода взглядов и самовыражения — 
    основные черты наших пользователей.
  </p> 
{% endblock %}

templates/pages/rules.html
{% extends "base.html" %}
{% block title %}
  Наши правила
{% endblock %}
{% block content %}
  <h1>Наши ценности</h1>
  <p>
    <b>Cамовыражение.</b> У наших пользователей должна 
    быть возможность создать что-то своё, выразить себя, 
    свои мысли и чувства.
  </p>
  <p>
    <b>Многообразие.</b> Мы уважаем и приветствуем разные 
    мнения и культуры. Блогикум — это место, объединяющее 
    самых разных людей. Поделитесь своим уникальным взглядом на мир.  
  </p>
  <p>
    <b>Творчество.</b> Не важно, в какой области вы творите, 
    это может быть литература, дизайн, программирование. 
    Наши инструменты помогут вам раскрыть талант максимально 
    просто и комфортно.   
  </p>
  <p>
    <b>Личность.</b> Мы сохраним ваши сокровенные мысли в тайне. 
    Делитесь своей информацией только с теми, кого выбрали. 
    Как и насколько засекречивать вашу личную информацию — 
    определяете вы и только вы.  
  </p>
{% endblock %}